package Vista;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class Vista extends javax.swing.JFrame {
    
    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        lbltoken15 = new javax.swing.JLabel();
        lbltoken16 = new javax.swing.JLabel();
        lbltoken14 = new javax.swing.JLabel();
        lbltoken13 = new javax.swing.JLabel();
        lbltoken12 = new javax.swing.JLabel();
        lbltoken17 = new javax.swing.JLabel();
        lbltoken11 = new javax.swing.JLabel();
        lbltoken10 = new javax.swing.JLabel();
        lbltoken37 = new javax.swing.JLabel();
        lbltoken31 = new javax.swing.JLabel();
        lbltoken30 = new javax.swing.JLabel();
        lbltoken35 = new javax.swing.JLabel();
        lbltoken36 = new javax.swing.JLabel();
        lbltoken34 = new javax.swing.JLabel();
        lbltoken33 = new javax.swing.JLabel();
        lbltoken32 = new javax.swing.JLabel();
        lbltoken41 = new javax.swing.JLabel();
        lbltoken46 = new javax.swing.JLabel();
        lbltoken40 = new javax.swing.JLabel();
        lbltoken44 = new javax.swing.JLabel();
        lbltoken42 = new javax.swing.JLabel();
        lbltoken47 = new javax.swing.JLabel();
        lbltoken45 = new javax.swing.JLabel();
        lbltoken43 = new javax.swing.JLabel();
        lbltoken53 = new javax.swing.JLabel();
        lbltoken50 = new javax.swing.JLabel();
        lbltoken54 = new javax.swing.JLabel();
        lbltoken55 = new javax.swing.JLabel();
        lbltoken56 = new javax.swing.JLabel();
        lbltoken51 = new javax.swing.JLabel();
        lbltoken52 = new javax.swing.JLabel();
        lbltoken57 = new javax.swing.JLabel();
        lbltoken22 = new javax.swing.JLabel();
        lbltoken27 = new javax.swing.JLabel();
        lbltoken21 = new javax.swing.JLabel();
        lbltoken20 = new javax.swing.JLabel();
        lbltoken25 = new javax.swing.JLabel();
        lbltoken26 = new javax.swing.JLabel();
        lbltoken24 = new javax.swing.JLabel();
        lbltoken23 = new javax.swing.JLabel();
        lbltoken02 = new javax.swing.JLabel();
        lbltoken07 = new javax.swing.JLabel();
        lbltoken01 = new javax.swing.JLabel();
        lbltoken00 = new javax.swing.JLabel();
        lbltoken05 = new javax.swing.JLabel();
        lbltoken06 = new javax.swing.JLabel();
        lbltoken04 = new javax.swing.JLabel();
        lbltoken03 = new javax.swing.JLabel();
        btncolumn0 = new javax.swing.JButton();
        btncolumn1 = new javax.swing.JButton();
        btncolumn2 = new javax.swing.JButton();
        btncolumn3 = new javax.swing.JButton();
        btncolumn4 = new javax.swing.JButton();
        btncolumn5 = new javax.swing.JButton();
        btncolumn6 = new javax.swing.JButton();
        btncolumn7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblturnoftext = new javax.swing.JLabel();
        lbltitleOrnameW = new javax.swing.JLabel();
        lbltitleOrwinner = new javax.swing.JLabel();
        lblplayerTurn = new javax.swing.JLabel();
        lbltokenTurn = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        lblcontWins1 = new javax.swing.JLabel();
        lblcontWins = new javax.swing.JLabel();
        lblcontWins2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        lbltoken15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken15.setText("jLabel2");

        lbltoken16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken16.setText("jLabel2");

        lbltoken14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken14.setText("jLabel2");

        lbltoken13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken13.setText("jLabel2");

        lbltoken12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken12.setText("jLabel2");

        lbltoken17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken17.setText("jLabel2");

        lbltoken11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken11.setText("jLabel2");

        lbltoken10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken10.setText("jLabel2");

        lbltoken37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken37.setText("jLabel2");

        lbltoken31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken31.setText("jLabel2");

        lbltoken30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken30.setText("jLabel2");

        lbltoken35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken35.setText("jLabel2");

        lbltoken36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken36.setText("jLabel2");

        lbltoken34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken34.setText("jLabel2");

        lbltoken33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken33.setText("jLabel2");

        lbltoken32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken32.setText("jLabel2");

        lbltoken41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken41.setText("jLabel2");

        lbltoken46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken46.setText("jLabel2");

        lbltoken40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken40.setText("jLabel2");

        lbltoken44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken44.setText("jLabel2");

        lbltoken42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken42.setText("jLabel2");

        lbltoken47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken47.setText("jLabel2");

        lbltoken45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken45.setText("jLabel2");

        lbltoken43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken43.setText("jLabel2");

        lbltoken53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken53.setText("jLabel2");

        lbltoken50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken50.setText("jLabel2");

        lbltoken54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken54.setText("jLabel2");

        lbltoken55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken55.setText("jLabel2");

        lbltoken56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken56.setText("jLabel2");

        lbltoken51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken51.setText("jLabel2");

        lbltoken52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken52.setText("jLabel2");

        lbltoken57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken57.setText("jLabel2");

        lbltoken22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken22.setText("jLabel2");

        lbltoken27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken27.setText("jLabel2");

        lbltoken21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken21.setText("jLabel2");

        lbltoken20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken20.setText("jLabel2");

        lbltoken25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken25.setText("jLabel2");

        lbltoken26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken26.setText("jLabel2");

        lbltoken24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken24.setText("jLabel2");

        lbltoken23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken23.setText("jLabel2");

        lbltoken02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken02.setText("jLabel2");

        lbltoken07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken07.setText("jLabel2");

        lbltoken01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken01.setText("jLabel2");

        lbltoken00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken00.setText("jLabel2");

        lbltoken05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken05.setText("jLabel2");

        lbltoken06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken06.setText("jLabel2");

        lbltoken04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken04.setText("jLabel2");

        lbltoken03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/blanco.png"))); // NOI18N
        lbltoken03.setText("jLabel2");

        btncolumn0.setBackground(new java.awt.Color(255, 102, 102));
        btncolumn0.setFont(new java.awt.Font("Book Antiqua", 1, 10)); // NOI18N
        btncolumn0.setForeground(new java.awt.Color(255, 255, 255));
        btncolumn0.setText("Insertar");

        btncolumn1.setBackground(new java.awt.Color(255, 102, 102));
        btncolumn1.setFont(new java.awt.Font("Book Antiqua", 1, 10)); // NOI18N
        btncolumn1.setForeground(new java.awt.Color(255, 255, 255));
        btncolumn1.setText("Insertar");

        btncolumn2.setBackground(new java.awt.Color(255, 102, 102));
        btncolumn2.setFont(new java.awt.Font("Book Antiqua", 1, 10)); // NOI18N
        btncolumn2.setForeground(new java.awt.Color(255, 255, 255));
        btncolumn2.setText("Insertar");

        btncolumn3.setBackground(new java.awt.Color(255, 102, 102));
        btncolumn3.setFont(new java.awt.Font("Book Antiqua", 1, 10)); // NOI18N
        btncolumn3.setForeground(new java.awt.Color(255, 255, 255));
        btncolumn3.setText("Insertar");

        btncolumn4.setBackground(new java.awt.Color(255, 102, 102));
        btncolumn4.setFont(new java.awt.Font("Book Antiqua", 1, 10)); // NOI18N
        btncolumn4.setForeground(new java.awt.Color(255, 255, 255));
        btncolumn4.setText("Insertar");

        btncolumn5.setBackground(new java.awt.Color(255, 102, 102));
        btncolumn5.setFont(new java.awt.Font("Book Antiqua", 1, 10)); // NOI18N
        btncolumn5.setForeground(new java.awt.Color(255, 255, 255));
        btncolumn5.setText("Insertar");

        btncolumn6.setBackground(new java.awt.Color(255, 102, 102));
        btncolumn6.setFont(new java.awt.Font("Book Antiqua", 1, 10)); // NOI18N
        btncolumn6.setForeground(new java.awt.Color(255, 255, 255));
        btncolumn6.setText("Insertar");

        btncolumn7.setBackground(new java.awt.Color(255, 102, 102));
        btncolumn7.setFont(new java.awt.Font("Book Antiqua", 1, 10)); // NOI18N
        btncolumn7.setForeground(new java.awt.Color(255, 255, 255));
        btncolumn7.setText("Insertar");

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblturnoftext.setFont(new java.awt.Font("Book Antiqua", 1, 10)); // NOI18N
        lblturnoftext.setText(" TURNO DE:");

        lbltitleOrnameW.setFont(new java.awt.Font("OCR A Extended", 1, 32)); // NOI18N
        lbltitleOrnameW.setForeground(new java.awt.Color(255, 0, 0));
        lbltitleOrnameW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitleOrnameW.setText("4 EN LÍNEA");

        lbltitleOrwinner.setFont(new java.awt.Font("OCR A Extended", 1, 32)); // NOI18N
        lbltitleOrwinner.setForeground(new java.awt.Color(0, 0, 153));
        lbltitleOrwinner.setText("4 EN LÍNEA");

        lblplayerTurn.setBackground(new java.awt.Color(255, 255, 255));
        lblplayerTurn.setFont(new java.awt.Font("Book Antiqua", 1, 10)); // NOI18N
        lblplayerTurn.setText("JUGADOR1");

        lbltokenTurn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokensph/azul.png"))); // NOI18N
        lbltokenTurn.setText("jLabel2");

        btnExit.setBackground(new java.awt.Color(153, 0, 255));
        btnExit.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("SALIR");
        btnExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblcontWins1.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        lblcontWins1.setText("2");

        lblcontWins.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        lblcontWins.setText("   :   ");

        lblcontWins2.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        lblcontWins2.setText("1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(lblturnoftext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblplayerTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lbltitleOrwinner, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(lbltokenTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lblcontWins1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcontWins)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcontWins2)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbltitleOrnameW, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcontWins1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcontWins, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcontWins2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblturnoftext)
                            .addComponent(lblplayerTurn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltokenTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbltitleOrnameW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbltitleOrwinner))
                        .addGap(36, 36, 36))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbltoken10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbltoken30, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken31, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbltoken40, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken41, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbltoken50, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken51, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbltoken20, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken21, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbltoken52, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken53, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken54, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken55, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken56, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken57, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbltoken12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken13, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken14, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken15, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken16, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken17, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbltoken32, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken33, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken34, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken35, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken36, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken37, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbltoken42, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken43, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken44, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken45, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken46, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken47, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbltoken22, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken23, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken24, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken25, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken26, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbltoken27, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbltoken00, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbltoken01, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbltoken02, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbltoken03, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbltoken04, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbltoken05, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbltoken06, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbltoken07, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btncolumn0, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btncolumn1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btncolumn2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btncolumn3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btncolumn4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btncolumn5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btncolumn6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btncolumn7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncolumn0, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncolumn1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncolumn2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncolumn3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncolumn4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncolumn5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncolumn6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncolumn7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltoken06)
                    .addComponent(lbltoken05)
                    .addComponent(lbltoken04)
                    .addComponent(lbltoken03)
                    .addComponent(lbltoken02)
                    .addComponent(lbltoken01)
                    .addComponent(lbltoken00)
                    .addComponent(lbltoken07))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltoken16)
                    .addComponent(lbltoken15)
                    .addComponent(lbltoken14)
                    .addComponent(lbltoken13)
                    .addComponent(lbltoken12)
                    .addComponent(lbltoken11)
                    .addComponent(lbltoken10)
                    .addComponent(lbltoken17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltoken26)
                    .addComponent(lbltoken25)
                    .addComponent(lbltoken24)
                    .addComponent(lbltoken23)
                    .addComponent(lbltoken22)
                    .addComponent(lbltoken21)
                    .addComponent(lbltoken20)
                    .addComponent(lbltoken27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltoken36)
                    .addComponent(lbltoken35)
                    .addComponent(lbltoken34)
                    .addComponent(lbltoken33)
                    .addComponent(lbltoken32)
                    .addComponent(lbltoken31)
                    .addComponent(lbltoken30)
                    .addComponent(lbltoken37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltoken46)
                    .addComponent(lbltoken45)
                    .addComponent(lbltoken44)
                    .addComponent(lbltoken43)
                    .addComponent(lbltoken42)
                    .addComponent(lbltoken41)
                    .addComponent(lbltoken40)
                    .addComponent(lbltoken47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltoken56)
                    .addComponent(lbltoken55)
                    .addComponent(lbltoken54)
                    .addComponent(lbltoken53)
                    .addComponent(lbltoken52)
                    .addComponent(lbltoken51)
                    .addComponent(lbltoken50)
                    .addComponent(lbltoken57))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnExit;
    public javax.swing.JButton btncolumn0;
    public javax.swing.JButton btncolumn1;
    public javax.swing.JButton btncolumn2;
    public javax.swing.JButton btncolumn3;
    public javax.swing.JButton btncolumn4;
    public javax.swing.JButton btncolumn5;
    public javax.swing.JButton btncolumn6;
    public javax.swing.JButton btncolumn7;
    private javax.swing.Box.Filler filler1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JLabel lblcontWins;
    public javax.swing.JLabel lblcontWins1;
    public javax.swing.JLabel lblcontWins2;
    public javax.swing.JLabel lblplayerTurn;
    public javax.swing.JLabel lbltitleOrnameW;
    public javax.swing.JLabel lbltitleOrwinner;
    public javax.swing.JLabel lbltoken00;
    public javax.swing.JLabel lbltoken01;
    public javax.swing.JLabel lbltoken02;
    public javax.swing.JLabel lbltoken03;
    public javax.swing.JLabel lbltoken04;
    public javax.swing.JLabel lbltoken05;
    public javax.swing.JLabel lbltoken06;
    public javax.swing.JLabel lbltoken07;
    public javax.swing.JLabel lbltoken10;
    public javax.swing.JLabel lbltoken11;
    public javax.swing.JLabel lbltoken12;
    public javax.swing.JLabel lbltoken13;
    public javax.swing.JLabel lbltoken14;
    public javax.swing.JLabel lbltoken15;
    public javax.swing.JLabel lbltoken16;
    public javax.swing.JLabel lbltoken17;
    public javax.swing.JLabel lbltoken20;
    public javax.swing.JLabel lbltoken21;
    public javax.swing.JLabel lbltoken22;
    public javax.swing.JLabel lbltoken23;
    public javax.swing.JLabel lbltoken24;
    public javax.swing.JLabel lbltoken25;
    public javax.swing.JLabel lbltoken26;
    public javax.swing.JLabel lbltoken27;
    public javax.swing.JLabel lbltoken30;
    public javax.swing.JLabel lbltoken31;
    public javax.swing.JLabel lbltoken32;
    public javax.swing.JLabel lbltoken33;
    public javax.swing.JLabel lbltoken34;
    public javax.swing.JLabel lbltoken35;
    public javax.swing.JLabel lbltoken36;
    public javax.swing.JLabel lbltoken37;
    public javax.swing.JLabel lbltoken40;
    public javax.swing.JLabel lbltoken41;
    public javax.swing.JLabel lbltoken42;
    public javax.swing.JLabel lbltoken43;
    public javax.swing.JLabel lbltoken44;
    public javax.swing.JLabel lbltoken45;
    public javax.swing.JLabel lbltoken46;
    public javax.swing.JLabel lbltoken47;
    public javax.swing.JLabel lbltoken50;
    public javax.swing.JLabel lbltoken51;
    public javax.swing.JLabel lbltoken52;
    public javax.swing.JLabel lbltoken53;
    public javax.swing.JLabel lbltoken54;
    public javax.swing.JLabel lbltoken55;
    public javax.swing.JLabel lbltoken56;
    public javax.swing.JLabel lbltoken57;
    public javax.swing.JLabel lbltokenTurn;
    public javax.swing.JLabel lblturnoftext;
    // End of variables declaration//GEN-END:variables

   
}
